<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "bobst_api"
 *
 * Auto generated by Extension Builder 2014-04-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title' => 'Ideative Tika',
	'description' => 'Extracts the content of a file',
	'category' => 'plugin',
	'author' => 'Ideative',
	'author_email' => 'support@ideative.ch',
	'author_company' => 'Jonathan Maire',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
